name: Generate Project

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install Cookiecutter
      run: pip install cookiecutter

    - name: Run Cookiecutter with Replay
      run: |
        git config --global user.name "github-actions[bot]"
        git config --global user.email "github-actions[bot]@users.noreply.github.com"
        COOKIECUTTER_REPO=https://github.com/weijia/cookiecutter-golang.git
        REPLAY_FILE=replay/initial_replay_file.json

        # Ensure the output directory exists
        mkdir -p generated_project
        cp -R /home/runner/work/iot-go-on-modern-os/iot-go-on-modern-os/.git generated_project/
        cp -R /home/runner/work/iot-go-on-modern-os/iot-go-on-modern-os/replay generated_project/
        # Run cookiecutter with the replay file
        cd generated_project
        cookiecutter $COOKIECUTTER_REPO --replay-file generated_project/$REPLAY_FILE --output-dir generated_project
        

    - name: Commit and push changes
      run: |
        cd generated_project
        git add .
        git commit -m "Generate project using Cookiecutter"
        git push
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
